# Generated by Django 5.2 on 2026-09-13 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('testcases', '0022_alter_testcasestep_expected_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='用例草稿', max_length=200)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('stage', models.CharField(default='等待处理', max_length=80)),
                ('input', models.JSONField(default=dict)),
                ('options', models.JSONField(default=dict)),
                ('cases', models.JSONField(default=list)),
                ('issues', models.JSONField(default=dict)),
                ('notes', models.JSONField(default=list)),
                ('saved_ids', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkbenchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.JSONField(default=list)),
                ('prompts', models.JSONField(default=dict)),
                ('stages', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CaseExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=64)),
                ('original', models.JSONField(default=dict)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guicase_extension', to='testcases.testcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guicase_workbench.generationjob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'source_key'), name='guicase_project_source_unique')],
            },
        ),
    ]
